name: Test container-diff Action

on: 
  pull_request: []

jobs:
  test-container-diff:
    name: Test container-diff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Add more test cases here as necessary
        args:
          - vanessa/salad --type=file --output=./data.json --json
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run container-diff
        uses: ./actions
        with:
          args: ${{ matrix.args }}
      - name: View output
        run: cat ./data.json
